### ISSUE TITLE
datepicker and fullcaendar problem for iran(persian-jalali)

### ISSUE THREAD

**Issue by saeed-raeisi** [OCA/l10n-iran#13]
hi
https://github.com/odoo/odoo/issues/72151
https://github.com/fullcalendar/fullcalendar/issues/6378

v14 -> commuinty -> fullcalendar problem
Tips for developing a jalali calendar

**Comment by saeed-raeisi** [comment]
https://github.com/odoo/odoo/issues/73599

**Comment by mostafabarmshory** [comment]
Dear Raesi,

Do you working on Jalali support in Odoo 14. I`m very interested to contribute.

**Comment by saeed-raeisi** [comment]
hi dear Mostafa
I would be very happy if you would cooperate
I will start the localization project soon

We intend to cooperate with Mr. Mahmoudi
https://github.com/parodoo/parOdoo

**Comment by saeed-raeisi** [comment]
> Dear Raesi,
> 
> Do you working on Jalali support in Odoo 14. I`m very interested to contribute.

hi dear Mostafa
I would be very happy if you would cooperate
I will start the localization project soon

We intend to cooperate with Mr. Mahmoudi
https://github.com/parodoo/parOdoo

**Comment by saeed-raeisi** [comment]
> Dear Raesi,
> 
> Do you working on Jalali support in Odoo 14. I`m very interested to contribute.

hi dear Mostafa
I would be very happy if you would cooperate
I start the localization project
https://github.com/FadooIR/l10n-iran

**Comment by mostafabarmshory** [comment]
Sound great
I`m newbie with odoo and do not know how to start. How can I help you, bro.

**Comment by saeed-raeisi** [comment]
Well, to start, the modules have to be phased
And localization modules should be developed for each phase

For example, the first step was the date and calendar that were solved

The second step is human resources
It's like employment and salaries and so on

**Comment by saeed-raeisi** [comment]
https://t.me/saeed_geek
Contact me on Telegram to join the group and explain the development process

**Comment by mostafabarmshory** [comment]
@saeed-raeisi 

I could not use telegram, sorry. Would you migrate to something else, such as slack, please?

**Comment by saeed-raeisi** [comment]
> @saeed-raeisi
> 
> I could not use telegram, sorry. Would you migrate to something else, such as slack, please?

We have an active board in trello
https://trello.com/invite/b/CebWi0P3/faf37bb6467dc155d5900017943e5dce/fadoo
Anyone with link can join as board member
