### ISSUE TITLE
monthly chart incorrect

### ISSUE THREAD

**Issue by j209** [OCA/l10n-iran#17]
Hi. thanks a lot for your works.

monthly charts incorrect

![Animation](https://user-images.githubusercontent.com/18129232/140641784-6ba9d54a-7077-45fa-b565-18f06c1add49.gif)

**Comment by saeed-raeisi** [comment]
Hi
The profile section should be set to a jalali calendar.
This section is written in the module description
The calendar is Gregorian by default unless we change it.

https://user-images.githubusercontent.com/38601142/140692303-67654c9b-00b8-44ba-9be3-793f02a69e8b.mp4

**Comment by j209** [comment]
persian:
تاریخ نمودارها با تاریخ اسناد تطابق ندارد.اسناد پرداخت مربوط به فروردین و اردیبهشت و خرداد 1400 ثبت شده اند ولی نمودارها یک ماه به عقب جابجا هستند

**Comment by saeed-raeisi** [comment]
En:
Yes that's right
This module simply converts the date label
The Persian calendar module is being tested and will be available soon.
---l10n_ir_web
date range
There is a problem with your search


Fa:

بله درسته
این ماژول صرفا لیبل تاریخ را تبدیل می کند
ماژول تقویم فارسی در حال تست است و به زودی قرار می گیرد.

محدوده زمانی
در جستجوی شما مشکل دارد

**Comment by j209** [comment]
When Persian calendar module probably will be available?

**Comment by saeed-raeisi** [comment]
> When Persian calendar module probably will be available?

Persian calendar module is ready. 
But it must be tested.

 On the other hand, the financial sector, ie payroll and accounting, are in priority 
And the fadoo team is constantly on the lookout for financial localization modules.

If you are interested in cooperating in financial localization, you can join us And later we will check the date and calendar sections.

**Comment by saeed-raeisi** [comment]
This issue is for a module that will be released soon
and for
 For this reason, the module will be closed until release.

**Comment by j209** [comment]
Hi
I could not see anything about "l10n_ir_web" on OCA runbot for testing.
