### ISSUE TITLE
تقویم جلالی

### ISSUE THREAD

**Issue by alisaeed** [OCA/l10n-iran#22]
سلام و عرض ادب
من ماژول تقویم شمسی را در odoo 14 و odoo 15نصب کردم اما کار نکرد. در پروفایل روبروی گزینه calender نوشته jalali موجود است اما قابل ویرایش نیست.
دیگر ماژول ها در odoo14 نصب میشوند اما Iran - Employee Contracts در نسخه 15 نصب نمی شود.
ممنون می شوم راهنمایی بفرمایید که چگونه تقویم جلالی را در نسخه 14 یا 15 راه اندازی کنم.
![jalali](https://user-images.githubusercontent.com/3950839/185999826-27a550cf-895b-45db-8a0c-d59c659613e9.PNG)

**Comment by saeed-raeisi** [comment]
سلام وقت بخیر
۱.ماژول l10n_ir_base فقط برای شمسی سازی تاریخ نمودار ها توسعه داده شده 
۲. بابت عدم نصب ماژول در ورژن ۱۵ - ماژول قرارداد کارمندان برای ورژن ۱۴ هست و هنوز روی نسخه ۱۵ توسعه داده نشده
۳. برای datepicker 
https://github.com/odoo-app-dev/jalaali
https://github.com/parodoo/parOdoo
برای نسخه ۱۵ از لینک اول و برای نسخه ۱۴ از لینک دوم اقدام کنید.

‌En:

Hello
1. The l10n_ir_base module was developed only for jalali the date of charts
2. For not installing the module in version 15 - the employee contract module is for version 14 and has not yet been developed for version 15
3. jalali datepicker 
https://github.com/odoo-app-dev/jalaali
https://github.com/parodoo/parOdoo
Apply for version 15 from the first link and for version 14 from the second link.

**Comment by saeed-raeisi** [comment]
در صورتی که علاقه مند بودید ماژول ها به ورژن ۱۵ ارتقا بدید و یک PR 
https://github.com/OCA/l10n-iran/tree/15.0
ارسال کنید.

**Comment by saeed-raeisi** [comment]
If your problems are solved, close this issue

Fa:
اگر مشکلات شما رفع شده است این Issue را ببندید

**Comment by siyamaksazgari-rgb** [comment]
سلام. تقویم جلالی برای ورژن 17 کجا میتونم پیدا کنم؟

**Comment by saeed-raeisi** [comment]
> سلام. تقویم جلالی برای ورژن 17 کجا میتونم پیدا کنم؟
سلام
https://odoo-community.ir/shop/73#attr=94
