### ISSUE TITLE
Installed but its not working

### ISSUE THREAD

**Issue by Maythemo** [OCA/l10n-iran#23]
## Module
10n_ir_base

## Describe the bug
installed all the modules l10n_ir_accounting,l10n_ir_base,l10n_ir_hr_contract,l10n_ir_states
![image](https://user-images.githubusercontent.com/112681744/188067007-f06c135d-9b1a-4d97-b2bb-4b4b61dd0cb4.png)
Cannot change the jalali there is no other options here.
![image](https://user-images.githubusercontent.com/112681744/188080507-0c833916-1b85-427b-bc33-5b1965c174f7.png)
I can see the jalali mount names only here and not any where else.
![image](https://user-images.githubusercontent.com/112681744/188083856-1802882c-ad26-4a25-8c81-d2ac8f7179f6.png)
none of  the dates and pickers are in jalali in any app

## To Reproduce
cloned the 14.0 
installed the l10n-iran
checked the calendars and dates

**Expected behavior**
jalali calendar date and picker at lease in some modules and apps

**Additional context**
ubuntu 20
odoo 14
l10n-iran 14.0.3
all latest modules and requirements

**Comment by saeed-raeisi** [comment]
Hi 
https://github.com/OCA/l10n-iran/issues/22

[The l10n_ir_base module was developed only for jalali the date of charts.](https://github.com/OCA/l10n-iran/blob/14.0/l10n_ir_base/readme/DESCRIPTION.rst)

jalali datepicker
https://github.com/odoo-app-dev/jalaali
https://github.com/parodoo/parOdoo

**Comment by saeed-raeisi** [comment]
If you are interested in these modules, you can
Submit a **PR** to be added to the repository

But no doubt they will be **rejected** by oca. I tried to add the jalali calendar module, but the oca rules prevent me from doing this.

replace standard library-> jalali support

**Comment by Maythemo** [comment]
Thank you .
Now I am in the route.
I will try my best

**Comment by saeed-raeisi** [comment]
> Thank you . Now I am in the route. I will try my best

Good luck
