### ISSUE TITLE
Migration to version 16.0

### ISSUE THREAD

**Issue by sbidoul** [OCA/l10n-iran#24]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-16.0

# Modules to migrate

Missing module? Check https://github.com/OCA/maintainer-tools/wiki/%5BFAQ%5D-Missing-modules-in-migration-issue-list

**Comment by saeed-raeisi** [comment]
[[MIG] l10n_ir_accounting](https://github.com/OCA/l10n-iran/commit/ee3f4a1e212d376fc89b8742307956481c749681)
[[MIG] l10n_ir_hr_contract](https://github.com/OCA/l10n-iran/commit/d79d813015e333ceb330b9b936ef1e6ebdd11a96)
[[MIG] l10n_ir_states](https://github.com/OCA/l10n-iran/commit/7b8cd9ff4574e90cc9509bb81ff07b9681a55bc7)
[[MIG] 14->16 l10n_ir](https://github.com/OCA/l10n-iran/commit/aa4300698104339be28fc83248216aaec911500f)

**Comment by saeed-raeisi** [comment]
Tested in Odoo 16 Enterprise

-  l10n_ir_accounting(The tax report has been removed and will be added soon)
-  l10n_ir_base(This module has been removed and will be added again after further review)
-  l10n_ir_hr_contract(The setting of default values ​​has been added and Iran's daily salary can be applied)

**Comment by saeed-raeisi** [comment]
@sbidoul 
Hello
Please change the default branch to 16.0

**Comment by saeed-raeisi** [comment]
[MIG] 14->16 l10n_ir https://github.com/OCA/l10n-iran/pull/25

**Comment by saeed-raeisi** [comment]
![image](https://user-images.githubusercontent.com/38601142/198989477-73165d17-633e-44c9-858b-a88cee88358d.png)

ERROR: Could not find a version that satisfies the requirement odoo14-addon-l10n-ir-accounting (unavailable) (from versions: 14.0.3.0.1.dev8)
ERROR: No matching distribution found for odoo14-addon-l10n-ir-accounting (unavailable)

Hello
Please change the default branch to 16
@sbidoul

**Comment by saeed-raeisi** [comment]
https://github.com/OCA/l10n-iran/pull/25
