### ISSUE TITLE
fiscal year

### ISSUE THREAD

**Issue by mrr-r** [OCA/l10n-iran#28]
Hi,
I'd like to convert fiscal year date to jalali.
Evrybody to know this please help me.
Thank's!

**Comment by saeed-raeisi** [comment]
سلام 
میتونید دو فیلد جدید برای مشخص کردن ماه و روز پایان سال مالی مشخص کنید
و سپس مقادیر دریافتی به میلادی تبدیل کنید و در فیلد های اصلی odoo ذخیره کنید
https://apps.odoo.com/apps/modules/15.0/l10n_ir_stock/

این موضوع در رابطه با ماژول های این ریپازیتوری نمیباشد
میتوانید یک ماژول برای این مورد توسعه بدید و در صورت تمایل pr بفرستید تا بقیه دوستان مشارکت کنن
