### ISSUE TITLE
bug in def _read_group_format_result

### ISSUE THREAD

**Issue by mrr-r** [OCA/l10n-iran#29]
سلام
در ماژول base ورژن 14 در قسمت کلاس def _read_group_format_result وقتی لیبل سال رو به جلالی کانورت می کنه سال رو یک سال عقبتر نشون می ده. لطفا بگید مشکل کجاست؟

**Comment by saeed-raeisi** [comment]
سلام وقت بخیر
از کتابخانه https://github.com/slashmili/python-jalali 
استفاده شده 
در واقع باگ نیست. گروه بندی سال و ماه اشتباه نمایش داده می شود
مثلا سال 2023 خروجی سال 1401 برای ماه ها نیز به همین شکل 

بابت این موضوع در کل راه حل l10n_ir_base اشتباه بوده و در ورژن ۱۶ حذف شده 
https://github.com/OCA/l10n-iran/tree/16.0


11 دی 1401
datetime(2023,1,1)
