### ISSUE TITLE
Persian calender in odio 16

### ISSUE THREAD

**Issue by Sanazzzmi** [OCA/l10n-iran#37]
Hello
Does the Persian calendar work on Odoo 16?

**Comment by saeed-raeisi** [comment]
Hi
https://github.com/omoghadasi/odoo_persian_datepicker
https://github.com/parodoo/parodoo

**Comment by saeed-raeisi** [comment]
https://github.com/h08831n/odoo-persian-date/
https://github.com/Hooshadoo-Co/l10n_ir_calendar
