### ISSUE TITLE
خطا در برخی قسمت ها توسط ماژول استان ها

### ISSUE THREAD

**Issue by danayen** [OCA/l10n-iran#40]
## ماژول
استان ها

## Describe the bug
وقتی ماژول استان ها نصب هست، یک خطایی در بخش افزودن حساب بانکی در ماژول حسابداری به شرح زیر می دهد:
The above server error caused the following client error:
RPC_ERROR: Arbitrary Uncaught Python Exception
    RPCError@http://localhost:8069/web/assets/028ee89/web.assets_web.min.js:2863:319
    makeErrorFromResponse@http://localhost:8069/web/assets/028ee89/web.assets_web.min.js:2866:163
    configureBlobDownloadXHR/xhr.onload/decoder.onload@http://localhost:8069
این اتفاق در اودو 17 افتاد. چند مورد در ورژن های 15 و 16 هم دیده بودم که ایراد از ماژول های بومی سازی بوده (حسابداری و استان)

## راهکار
ماژول بومی سازی رو "حذف نصب" (uninstall) کنید درست میشه.

**Comment by saeed-raeisi** [comment]
account_online_synchronization
Add A Bank Account ?
_fetch_odoo_fin -> fetch data from the Odoo Fin proxy

**Comment by danayen** [comment]
من امروز به صورت اتفاقی فهمیدم که این خطا مربوط به اینترنت هست!
وقتی با فیلترشکن استفاده کردم، این خطا رو نداد و به درستی کار کرد. همین مشکل موقع چاپ صورتحساب هم هست.
نمیدونم راهکاری هست یا نه. (شکن هم تنظیم بود روی سرور)

**Comment by danayen** [comment]
یه چند روزی بود درگیر مازول حسابداری و افزودن حساب بانکی بودم.
در ماژول "صدور فاکتور" به راحتی میشد "افزودن حساب بانکی" رو کلیک کرده و حساب رو اضافه کرد. ولی وقتی ماژول حسابداری رو نصب میکردم، این گزینه خطا میداد. حتی وقتی نصب رو غیرفعال میکردم هم همان مشکل وجود داشت.

بعد کلی گشتن و آزمون و ... بالاخره این طوری رفع شد:
1- ماژول رو نصب کنید تا دیتا و بومی سازی انجام بشه
2- ماژول رو حذف نصب کنید (دیتای نصب شده از بین نمیره)
3- ماژول رو از پوشه addons حذف کامل کنید.
4- از ماژول برنامه ها، لیست ماژول ها رو اپدیت کنید. ترجیحا سرویس اودو رو ریستارت کنید.

امیدوارم دولوپرهای عزیز این مورد رو در نسخه فعلی یا بعدی در نظر بگیرند. ظاهرا تداخل ایجاد میشه بین ماژول ها (بین ln10-account و ماژول حسابداری). چی و کجاش رو نمیدونم.
همچنین اگر حوصله داشتید، کدینگ های حسابداری رو هم یه اپدیت کنیم برای استاندارد ایران. منم سعی میکنم تا جایی که بلد باشم کمک کنم.
